/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocktim.h"

static const char* CMockString_MX_TIM6_Init = "MX_TIM6_Init";

typedef struct _CMOCK_MX_TIM6_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_MX_TIM6_Init_CALL_INSTANCE;

static struct MocktimInstance
{
  char MX_TIM6_Init_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE MX_TIM6_Init_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocktim_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.MX_TIM6_Init_CallInstance;
  if (Mock.MX_TIM6_Init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MX_TIM6_Init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mocktim_Init(void)
{
  Mocktim_Destroy();
}

void Mocktim_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void MX_TIM6_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MX_TIM6_Init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MX_TIM6_Init);
  cmock_call_instance = (CMOCK_MX_TIM6_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MX_TIM6_Init_CallInstance);
  Mock.MX_TIM6_Init_CallInstance = CMock_Guts_MemNext(Mock.MX_TIM6_Init_CallInstance);
  if (Mock.MX_TIM6_Init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void MX_TIM6_Init_CMockIgnore(void)
{
  Mock.MX_TIM6_Init_IgnoreBool = (char)1;
}

void MX_TIM6_Init_CMockStopIgnore(void)
{
  Mock.MX_TIM6_Init_IgnoreBool = (char)0;
}

void MX_TIM6_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MX_TIM6_Init_CALL_INSTANCE));
  CMOCK_MX_TIM6_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_MX_TIM6_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MX_TIM6_Init_CallInstance = CMock_Guts_MemChain(Mock.MX_TIM6_Init_CallInstance, cmock_guts_index);
  Mock.MX_TIM6_Init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

