/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockidentity.h"

static const char* CMockString_byte_size = "byte_size";
static const char* CMockString_id = "id";
static const char* CMockString_identity_get_build_time = "identity_get_build_time";
static const char* CMockString_identity_get_can_payload = "identity_get_can_payload";
static const char* CMockString_identity_get_cellboard_id = "identity_get_cellboard_id";
static const char* CMockString_identity_get_string_build_time = "identity_get_string_build_time";
static const char* CMockString_identity_init = "identity_init";

typedef struct _CMOCK_identity_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CellboardId Expected_id;

} CMOCK_identity_init_CALL_INSTANCE;

typedef struct _CMOCK_identity_get_cellboard_id_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CellboardId ReturnVal;

} CMOCK_identity_get_cellboard_id_CALL_INSTANCE;

typedef struct _CMOCK_identity_get_build_time_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  milliseconds_t ReturnVal;

} CMOCK_identity_get_build_time_CALL_INSTANCE;

typedef struct _CMOCK_identity_get_string_build_time_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* ReturnVal;

} CMOCK_identity_get_string_build_time_CALL_INSTANCE;

typedef struct _CMOCK_identity_get_can_payload_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bms_cellboard_version_converted_t* ReturnVal;
  size_t* Expected_byte_size;

} CMOCK_identity_get_can_payload_CALL_INSTANCE;

static struct MockidentityInstance
{
  CMOCK_MEM_INDEX_TYPE identity_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE identity_get_cellboard_id_CallInstance;
  CMOCK_MEM_INDEX_TYPE identity_get_build_time_CallInstance;
  CMOCK_MEM_INDEX_TYPE identity_get_string_build_time_CallInstance;
  CMOCK_MEM_INDEX_TYPE identity_get_can_payload_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockidentity_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.identity_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_identity_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.identity_get_cellboard_id_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_identity_get_cellboard_id);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.identity_get_build_time_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_identity_get_build_time);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.identity_get_string_build_time_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_identity_get_string_build_time);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.identity_get_can_payload_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_identity_get_can_payload);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockidentity_Init(void)
{
  Mockidentity_Destroy();
}

void Mockidentity_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void identity_init(CellboardId id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_identity_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_identity_init);
  cmock_call_instance = (CMOCK_identity_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.identity_init_CallInstance);
  Mock.identity_init_CallInstance = CMock_Guts_MemNext(Mock.identity_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_identity_init,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(CellboardId), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_identity_init(CMOCK_identity_init_CALL_INSTANCE* cmock_call_instance, CellboardId id);
void CMockExpectParameters_identity_init(CMOCK_identity_init_CALL_INSTANCE* cmock_call_instance, CellboardId id)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(CellboardId[sizeof(id) == sizeof(CellboardId) ? 1 : -1])); /* add CellboardId to :treat_as_array if this causes an error */
}

void identity_init_CMockExpect(UNITY_LINE_TYPE cmock_line, CellboardId id)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_identity_init_CALL_INSTANCE));
  CMOCK_identity_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_identity_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.identity_init_CallInstance = CMock_Guts_MemChain(Mock.identity_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_identity_init(cmock_call_instance, id);
}

CellboardId identity_get_cellboard_id(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_identity_get_cellboard_id_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_identity_get_cellboard_id);
  cmock_call_instance = (CMOCK_identity_get_cellboard_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.identity_get_cellboard_id_CallInstance);
  Mock.identity_get_cellboard_id_CallInstance = CMock_Guts_MemNext(Mock.identity_get_cellboard_id_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void identity_get_cellboard_id_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CellboardId cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_identity_get_cellboard_id_CALL_INSTANCE));
  CMOCK_identity_get_cellboard_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_identity_get_cellboard_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.identity_get_cellboard_id_CallInstance = CMock_Guts_MemChain(Mock.identity_get_cellboard_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(CellboardId[sizeof(cmock_to_return) == sizeof(CellboardId) ? 1 : -1])); /* add CellboardId to :treat_as_array if this causes an error */
}

milliseconds_t identity_get_build_time(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_identity_get_build_time_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_identity_get_build_time);
  cmock_call_instance = (CMOCK_identity_get_build_time_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.identity_get_build_time_CallInstance);
  Mock.identity_get_build_time_CallInstance = CMock_Guts_MemNext(Mock.identity_get_build_time_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void identity_get_build_time_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, milliseconds_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_identity_get_build_time_CALL_INSTANCE));
  CMOCK_identity_get_build_time_CALL_INSTANCE* cmock_call_instance = (CMOCK_identity_get_build_time_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.identity_get_build_time_CallInstance = CMock_Guts_MemChain(Mock.identity_get_build_time_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(milliseconds_t[sizeof(cmock_to_return) == sizeof(milliseconds_t) ? 1 : -1])); /* add milliseconds_t to :treat_as_array if this causes an error */
}

char* identity_get_string_build_time(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_identity_get_string_build_time_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_identity_get_string_build_time);
  cmock_call_instance = (CMOCK_identity_get_string_build_time_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.identity_get_string_build_time_CallInstance);
  Mock.identity_get_string_build_time_CallInstance = CMock_Guts_MemNext(Mock.identity_get_string_build_time_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void identity_get_string_build_time_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_identity_get_string_build_time_CALL_INSTANCE));
  CMOCK_identity_get_string_build_time_CALL_INSTANCE* cmock_call_instance = (CMOCK_identity_get_string_build_time_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.identity_get_string_build_time_CallInstance = CMock_Guts_MemChain(Mock.identity_get_string_build_time_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bms_cellboard_version_converted_t* identity_get_can_payload(size_t* byte_size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_identity_get_can_payload_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_identity_get_can_payload);
  cmock_call_instance = (CMOCK_identity_get_can_payload_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.identity_get_can_payload_CallInstance);
  Mock.identity_get_can_payload_CallInstance = CMock_Guts_MemNext(Mock.identity_get_can_payload_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_identity_get_can_payload,CMockString_byte_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_byte_size), (void*)(byte_size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_identity_get_can_payload(CMOCK_identity_get_can_payload_CALL_INSTANCE* cmock_call_instance, size_t* byte_size);
void CMockExpectParameters_identity_get_can_payload(CMOCK_identity_get_can_payload_CALL_INSTANCE* cmock_call_instance, size_t* byte_size)
{
  cmock_call_instance->Expected_byte_size = byte_size;
}

void identity_get_can_payload_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t* byte_size, bms_cellboard_version_converted_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_identity_get_can_payload_CALL_INSTANCE));
  CMOCK_identity_get_can_payload_CALL_INSTANCE* cmock_call_instance = (CMOCK_identity_get_can_payload_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.identity_get_can_payload_CallInstance = CMock_Guts_MemChain(Mock.identity_get_can_payload_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_identity_get_can_payload(cmock_call_instance, byte_size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

