/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSTM32G4XX_HAL_CONF_H
#define _MOCKSTM32G4XX_HAL_CONF_H

#include "unity.h"
#include "stm32g4xx_hal_conf.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockstm32g4xx_hal_conf_Init(void);
void Mockstm32g4xx_hal_conf_Destroy(void);
void Mockstm32g4xx_hal_conf_Verify(void);




#define assert_failed_Ignore() assert_failed_CMockIgnore()
void assert_failed_CMockIgnore(void);
#define assert_failed_StopIgnore() assert_failed_CMockStopIgnore()
void assert_failed_CMockStopIgnore(void);
#define assert_failed_Expect(file, line) assert_failed_CMockExpect(__LINE__, file, line)
void assert_failed_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t* file, uint32_t line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
