/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockgpio.h"

static const char* CMockString_MX_GPIO_Init = "MX_GPIO_Init";
static const char* CMockString_gpio_led_set_state = "gpio_led_set_state";
static const char* CMockString_gpio_led_toggle_state = "gpio_led_toggle_state";
static const char* CMockString_state = "state";

typedef struct _CMOCK_MX_GPIO_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_MX_GPIO_Init_CALL_INSTANCE;

typedef struct _CMOCK_gpio_led_set_state_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  LedStatus Expected_state;

} CMOCK_gpio_led_set_state_CALL_INSTANCE;

typedef struct _CMOCK_gpio_led_toggle_state_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_gpio_led_toggle_state_CALL_INSTANCE;

static struct MockgpioInstance
{
  char MX_GPIO_Init_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE MX_GPIO_Init_CallInstance;
  char gpio_led_set_state_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE gpio_led_set_state_CallInstance;
  char gpio_led_toggle_state_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE gpio_led_toggle_state_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockgpio_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.MX_GPIO_Init_CallInstance;
  if (Mock.MX_GPIO_Init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MX_GPIO_Init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.gpio_led_set_state_CallInstance;
  if (Mock.gpio_led_set_state_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_gpio_led_set_state);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.gpio_led_toggle_state_CallInstance;
  if (Mock.gpio_led_toggle_state_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_gpio_led_toggle_state);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockgpio_Init(void)
{
  Mockgpio_Destroy();
}

void Mockgpio_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void MX_GPIO_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MX_GPIO_Init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MX_GPIO_Init);
  cmock_call_instance = (CMOCK_MX_GPIO_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MX_GPIO_Init_CallInstance);
  Mock.MX_GPIO_Init_CallInstance = CMock_Guts_MemNext(Mock.MX_GPIO_Init_CallInstance);
  if (Mock.MX_GPIO_Init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void MX_GPIO_Init_CMockIgnore(void)
{
  Mock.MX_GPIO_Init_IgnoreBool = (char)1;
}

void MX_GPIO_Init_CMockStopIgnore(void)
{
  Mock.MX_GPIO_Init_IgnoreBool = (char)0;
}

void MX_GPIO_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MX_GPIO_Init_CALL_INSTANCE));
  CMOCK_MX_GPIO_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_MX_GPIO_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MX_GPIO_Init_CallInstance = CMock_Guts_MemChain(Mock.MX_GPIO_Init_CallInstance, cmock_guts_index);
  Mock.MX_GPIO_Init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void gpio_led_set_state(LedStatus state)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gpio_led_set_state_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_gpio_led_set_state);
  cmock_call_instance = (CMOCK_gpio_led_set_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gpio_led_set_state_CallInstance);
  Mock.gpio_led_set_state_CallInstance = CMock_Guts_MemNext(Mock.gpio_led_set_state_CallInstance);
  if (Mock.gpio_led_set_state_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_gpio_led_set_state,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(LedStatus), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_gpio_led_set_state(CMOCK_gpio_led_set_state_CALL_INSTANCE* cmock_call_instance, LedStatus state);
void CMockExpectParameters_gpio_led_set_state(CMOCK_gpio_led_set_state_CALL_INSTANCE* cmock_call_instance, LedStatus state)
{
  memcpy((void*)(&cmock_call_instance->Expected_state), (void*)(&state),
         sizeof(LedStatus[sizeof(state) == sizeof(LedStatus) ? 1 : -1])); /* add LedStatus to :treat_as_array if this causes an error */
}

void gpio_led_set_state_CMockIgnore(void)
{
  Mock.gpio_led_set_state_IgnoreBool = (char)1;
}

void gpio_led_set_state_CMockStopIgnore(void)
{
  Mock.gpio_led_set_state_IgnoreBool = (char)0;
}

void gpio_led_set_state_CMockExpect(UNITY_LINE_TYPE cmock_line, LedStatus state)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_led_set_state_CALL_INSTANCE));
  CMOCK_gpio_led_set_state_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_led_set_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_led_set_state_CallInstance = CMock_Guts_MemChain(Mock.gpio_led_set_state_CallInstance, cmock_guts_index);
  Mock.gpio_led_set_state_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_gpio_led_set_state(cmock_call_instance, state);
}

void gpio_led_toggle_state(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gpio_led_toggle_state_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_gpio_led_toggle_state);
  cmock_call_instance = (CMOCK_gpio_led_toggle_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gpio_led_toggle_state_CallInstance);
  Mock.gpio_led_toggle_state_CallInstance = CMock_Guts_MemNext(Mock.gpio_led_toggle_state_CallInstance);
  if (Mock.gpio_led_toggle_state_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void gpio_led_toggle_state_CMockIgnore(void)
{
  Mock.gpio_led_toggle_state_IgnoreBool = (char)1;
}

void gpio_led_toggle_state_CMockStopIgnore(void)
{
  Mock.gpio_led_toggle_state_IgnoreBool = (char)0;
}

void gpio_led_toggle_state_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_led_toggle_state_CALL_INSTANCE));
  CMOCK_gpio_led_toggle_state_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_led_toggle_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_led_toggle_state_CallInstance = CMock_Guts_MemChain(Mock.gpio_led_toggle_state_CallInstance, cmock_guts_index);
  Mock.gpio_led_toggle_state_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

