/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKFDCAN_H
#define _MOCKFDCAN_H

#include "unity.h"
#include "fdcan.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockfdcan_Init(void);
void Mockfdcan_Destroy(void);
void Mockfdcan_Verify(void);




#define MX_FDCAN1_Init_Ignore() MX_FDCAN1_Init_CMockIgnore()
void MX_FDCAN1_Init_CMockIgnore(void);
#define MX_FDCAN1_Init_StopIgnore() MX_FDCAN1_Init_CMockStopIgnore()
void MX_FDCAN1_Init_CMockStopIgnore(void);
#define MX_FDCAN1_Init_Expect() MX_FDCAN1_Init_CMockExpect(__LINE__)
void MX_FDCAN1_Init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define can_send_IgnoreAndReturn(cmock_retval) can_send_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void can_send_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, CanCommReturnCode cmock_to_return);
#define can_send_StopIgnore() can_send_CMockStopIgnore()
void can_send_CMockStopIgnore(void);
#define can_send_ExpectAndReturn(id, frame_type, data, size, cmock_retval) can_send_CMockExpectAndReturn(__LINE__, id, frame_type, data, size, cmock_retval)
void can_send_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, can_id_t id, CanFrameType frame_type, const uint8_t* data, size_t size, CanCommReturnCode cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
