/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKUSART_H
#define _MOCKUSART_H

#include "unity.h"
#include "usart.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockusart_Init(void);
void Mockusart_Destroy(void);
void Mockusart_Verify(void);




#define MX_USART2_UART_Init_Ignore() MX_USART2_UART_Init_CMockIgnore()
void MX_USART2_UART_Init_CMockIgnore(void);
#define MX_USART2_UART_Init_StopIgnore() MX_USART2_UART_Init_CMockStopIgnore()
void MX_USART2_UART_Init_CMockStopIgnore(void);
#define MX_USART2_UART_Init_Expect() MX_USART2_UART_Init_CMockExpect(__LINE__)
void MX_USART2_UART_Init_CMockExpect(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
