/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockstm32g4xx_it.h"

static const char* CMockString_BusFault_Handler = "BusFault_Handler";
static const char* CMockString_DebugMon_Handler = "DebugMon_Handler";
static const char* CMockString_HardFault_Handler = "HardFault_Handler";
static const char* CMockString_MemManage_Handler = "MemManage_Handler";
static const char* CMockString_NMI_Handler = "NMI_Handler";
static const char* CMockString_PendSV_Handler = "PendSV_Handler";
static const char* CMockString_SVC_Handler = "SVC_Handler";
static const char* CMockString_SysTick_Handler = "SysTick_Handler";
static const char* CMockString_UsageFault_Handler = "UsageFault_Handler";
static const char* CMockString_it_cs_enter = "it_cs_enter";
static const char* CMockString_it_cs_exit = "it_cs_exit";

typedef struct _CMOCK_NMI_Handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_NMI_Handler_CALL_INSTANCE;

typedef struct _CMOCK_HardFault_Handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HardFault_Handler_CALL_INSTANCE;

typedef struct _CMOCK_MemManage_Handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_MemManage_Handler_CALL_INSTANCE;

typedef struct _CMOCK_BusFault_Handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_BusFault_Handler_CALL_INSTANCE;

typedef struct _CMOCK_UsageFault_Handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_UsageFault_Handler_CALL_INSTANCE;

typedef struct _CMOCK_SVC_Handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_SVC_Handler_CALL_INSTANCE;

typedef struct _CMOCK_DebugMon_Handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_DebugMon_Handler_CALL_INSTANCE;

typedef struct _CMOCK_PendSV_Handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_PendSV_Handler_CALL_INSTANCE;

typedef struct _CMOCK_SysTick_Handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_SysTick_Handler_CALL_INSTANCE;

typedef struct _CMOCK_it_cs_enter_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_it_cs_enter_CALL_INSTANCE;

typedef struct _CMOCK_it_cs_exit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_it_cs_exit_CALL_INSTANCE;

static struct Mockstm32g4xx_itInstance
{
  char NMI_Handler_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE NMI_Handler_CallInstance;
  char HardFault_Handler_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE HardFault_Handler_CallInstance;
  char MemManage_Handler_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE MemManage_Handler_CallInstance;
  char BusFault_Handler_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE BusFault_Handler_CallInstance;
  char UsageFault_Handler_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE UsageFault_Handler_CallInstance;
  char SVC_Handler_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SVC_Handler_CallInstance;
  char DebugMon_Handler_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE DebugMon_Handler_CallInstance;
  char PendSV_Handler_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE PendSV_Handler_CallInstance;
  char SysTick_Handler_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SysTick_Handler_CallInstance;
  char it_cs_enter_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE it_cs_enter_CallInstance;
  char it_cs_exit_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE it_cs_exit_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockstm32g4xx_it_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.NMI_Handler_CallInstance;
  if (Mock.NMI_Handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_NMI_Handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HardFault_Handler_CallInstance;
  if (Mock.HardFault_Handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HardFault_Handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.MemManage_Handler_CallInstance;
  if (Mock.MemManage_Handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MemManage_Handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.BusFault_Handler_CallInstance;
  if (Mock.BusFault_Handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_BusFault_Handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.UsageFault_Handler_CallInstance;
  if (Mock.UsageFault_Handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_UsageFault_Handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SVC_Handler_CallInstance;
  if (Mock.SVC_Handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SVC_Handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.DebugMon_Handler_CallInstance;
  if (Mock.DebugMon_Handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_DebugMon_Handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.PendSV_Handler_CallInstance;
  if (Mock.PendSV_Handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_PendSV_Handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SysTick_Handler_CallInstance;
  if (Mock.SysTick_Handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SysTick_Handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.it_cs_enter_CallInstance;
  if (Mock.it_cs_enter_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_it_cs_enter);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.it_cs_exit_CallInstance;
  if (Mock.it_cs_exit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_it_cs_exit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockstm32g4xx_it_Init(void)
{
  Mockstm32g4xx_it_Destroy();
}

void Mockstm32g4xx_it_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void NMI_Handler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_NMI_Handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_NMI_Handler);
  cmock_call_instance = (CMOCK_NMI_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.NMI_Handler_CallInstance);
  Mock.NMI_Handler_CallInstance = CMock_Guts_MemNext(Mock.NMI_Handler_CallInstance);
  if (Mock.NMI_Handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void NMI_Handler_CMockIgnore(void)
{
  Mock.NMI_Handler_IgnoreBool = (char)1;
}

void NMI_Handler_CMockStopIgnore(void)
{
  Mock.NMI_Handler_IgnoreBool = (char)0;
}

void NMI_Handler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_NMI_Handler_CALL_INSTANCE));
  CMOCK_NMI_Handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_NMI_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.NMI_Handler_CallInstance = CMock_Guts_MemChain(Mock.NMI_Handler_CallInstance, cmock_guts_index);
  Mock.NMI_Handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void HardFault_Handler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HardFault_Handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HardFault_Handler);
  cmock_call_instance = (CMOCK_HardFault_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HardFault_Handler_CallInstance);
  Mock.HardFault_Handler_CallInstance = CMock_Guts_MemNext(Mock.HardFault_Handler_CallInstance);
  if (Mock.HardFault_Handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HardFault_Handler_CMockIgnore(void)
{
  Mock.HardFault_Handler_IgnoreBool = (char)1;
}

void HardFault_Handler_CMockStopIgnore(void)
{
  Mock.HardFault_Handler_IgnoreBool = (char)0;
}

void HardFault_Handler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HardFault_Handler_CALL_INSTANCE));
  CMOCK_HardFault_Handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_HardFault_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HardFault_Handler_CallInstance = CMock_Guts_MemChain(Mock.HardFault_Handler_CallInstance, cmock_guts_index);
  Mock.HardFault_Handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void MemManage_Handler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MemManage_Handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MemManage_Handler);
  cmock_call_instance = (CMOCK_MemManage_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MemManage_Handler_CallInstance);
  Mock.MemManage_Handler_CallInstance = CMock_Guts_MemNext(Mock.MemManage_Handler_CallInstance);
  if (Mock.MemManage_Handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void MemManage_Handler_CMockIgnore(void)
{
  Mock.MemManage_Handler_IgnoreBool = (char)1;
}

void MemManage_Handler_CMockStopIgnore(void)
{
  Mock.MemManage_Handler_IgnoreBool = (char)0;
}

void MemManage_Handler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MemManage_Handler_CALL_INSTANCE));
  CMOCK_MemManage_Handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_MemManage_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MemManage_Handler_CallInstance = CMock_Guts_MemChain(Mock.MemManage_Handler_CallInstance, cmock_guts_index);
  Mock.MemManage_Handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void BusFault_Handler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_BusFault_Handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_BusFault_Handler);
  cmock_call_instance = (CMOCK_BusFault_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.BusFault_Handler_CallInstance);
  Mock.BusFault_Handler_CallInstance = CMock_Guts_MemNext(Mock.BusFault_Handler_CallInstance);
  if (Mock.BusFault_Handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void BusFault_Handler_CMockIgnore(void)
{
  Mock.BusFault_Handler_IgnoreBool = (char)1;
}

void BusFault_Handler_CMockStopIgnore(void)
{
  Mock.BusFault_Handler_IgnoreBool = (char)0;
}

void BusFault_Handler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BusFault_Handler_CALL_INSTANCE));
  CMOCK_BusFault_Handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_BusFault_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BusFault_Handler_CallInstance = CMock_Guts_MemChain(Mock.BusFault_Handler_CallInstance, cmock_guts_index);
  Mock.BusFault_Handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void UsageFault_Handler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UsageFault_Handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_UsageFault_Handler);
  cmock_call_instance = (CMOCK_UsageFault_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UsageFault_Handler_CallInstance);
  Mock.UsageFault_Handler_CallInstance = CMock_Guts_MemNext(Mock.UsageFault_Handler_CallInstance);
  if (Mock.UsageFault_Handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void UsageFault_Handler_CMockIgnore(void)
{
  Mock.UsageFault_Handler_IgnoreBool = (char)1;
}

void UsageFault_Handler_CMockStopIgnore(void)
{
  Mock.UsageFault_Handler_IgnoreBool = (char)0;
}

void UsageFault_Handler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UsageFault_Handler_CALL_INSTANCE));
  CMOCK_UsageFault_Handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_UsageFault_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UsageFault_Handler_CallInstance = CMock_Guts_MemChain(Mock.UsageFault_Handler_CallInstance, cmock_guts_index);
  Mock.UsageFault_Handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void SVC_Handler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SVC_Handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SVC_Handler);
  cmock_call_instance = (CMOCK_SVC_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SVC_Handler_CallInstance);
  Mock.SVC_Handler_CallInstance = CMock_Guts_MemNext(Mock.SVC_Handler_CallInstance);
  if (Mock.SVC_Handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void SVC_Handler_CMockIgnore(void)
{
  Mock.SVC_Handler_IgnoreBool = (char)1;
}

void SVC_Handler_CMockStopIgnore(void)
{
  Mock.SVC_Handler_IgnoreBool = (char)0;
}

void SVC_Handler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SVC_Handler_CALL_INSTANCE));
  CMOCK_SVC_Handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_SVC_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SVC_Handler_CallInstance = CMock_Guts_MemChain(Mock.SVC_Handler_CallInstance, cmock_guts_index);
  Mock.SVC_Handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void DebugMon_Handler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_DebugMon_Handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_DebugMon_Handler);
  cmock_call_instance = (CMOCK_DebugMon_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.DebugMon_Handler_CallInstance);
  Mock.DebugMon_Handler_CallInstance = CMock_Guts_MemNext(Mock.DebugMon_Handler_CallInstance);
  if (Mock.DebugMon_Handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void DebugMon_Handler_CMockIgnore(void)
{
  Mock.DebugMon_Handler_IgnoreBool = (char)1;
}

void DebugMon_Handler_CMockStopIgnore(void)
{
  Mock.DebugMon_Handler_IgnoreBool = (char)0;
}

void DebugMon_Handler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DebugMon_Handler_CALL_INSTANCE));
  CMOCK_DebugMon_Handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_DebugMon_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.DebugMon_Handler_CallInstance = CMock_Guts_MemChain(Mock.DebugMon_Handler_CallInstance, cmock_guts_index);
  Mock.DebugMon_Handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void PendSV_Handler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_PendSV_Handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_PendSV_Handler);
  cmock_call_instance = (CMOCK_PendSV_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PendSV_Handler_CallInstance);
  Mock.PendSV_Handler_CallInstance = CMock_Guts_MemNext(Mock.PendSV_Handler_CallInstance);
  if (Mock.PendSV_Handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void PendSV_Handler_CMockIgnore(void)
{
  Mock.PendSV_Handler_IgnoreBool = (char)1;
}

void PendSV_Handler_CMockStopIgnore(void)
{
  Mock.PendSV_Handler_IgnoreBool = (char)0;
}

void PendSV_Handler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PendSV_Handler_CALL_INSTANCE));
  CMOCK_PendSV_Handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_PendSV_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PendSV_Handler_CallInstance = CMock_Guts_MemChain(Mock.PendSV_Handler_CallInstance, cmock_guts_index);
  Mock.PendSV_Handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void SysTick_Handler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SysTick_Handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SysTick_Handler);
  cmock_call_instance = (CMOCK_SysTick_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SysTick_Handler_CallInstance);
  Mock.SysTick_Handler_CallInstance = CMock_Guts_MemNext(Mock.SysTick_Handler_CallInstance);
  if (Mock.SysTick_Handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void SysTick_Handler_CMockIgnore(void)
{
  Mock.SysTick_Handler_IgnoreBool = (char)1;
}

void SysTick_Handler_CMockStopIgnore(void)
{
  Mock.SysTick_Handler_IgnoreBool = (char)0;
}

void SysTick_Handler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SysTick_Handler_CALL_INSTANCE));
  CMOCK_SysTick_Handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_SysTick_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SysTick_Handler_CallInstance = CMock_Guts_MemChain(Mock.SysTick_Handler_CallInstance, cmock_guts_index);
  Mock.SysTick_Handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void it_cs_enter(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_it_cs_enter_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_it_cs_enter);
  cmock_call_instance = (CMOCK_it_cs_enter_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.it_cs_enter_CallInstance);
  Mock.it_cs_enter_CallInstance = CMock_Guts_MemNext(Mock.it_cs_enter_CallInstance);
  if (Mock.it_cs_enter_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void it_cs_enter_CMockIgnore(void)
{
  Mock.it_cs_enter_IgnoreBool = (char)1;
}

void it_cs_enter_CMockStopIgnore(void)
{
  Mock.it_cs_enter_IgnoreBool = (char)0;
}

void it_cs_enter_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_it_cs_enter_CALL_INSTANCE));
  CMOCK_it_cs_enter_CALL_INSTANCE* cmock_call_instance = (CMOCK_it_cs_enter_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.it_cs_enter_CallInstance = CMock_Guts_MemChain(Mock.it_cs_enter_CallInstance, cmock_guts_index);
  Mock.it_cs_enter_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void it_cs_exit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_it_cs_exit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_it_cs_exit);
  cmock_call_instance = (CMOCK_it_cs_exit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.it_cs_exit_CallInstance);
  Mock.it_cs_exit_CallInstance = CMock_Guts_MemNext(Mock.it_cs_exit_CallInstance);
  if (Mock.it_cs_exit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void it_cs_exit_CMockIgnore(void)
{
  Mock.it_cs_exit_IgnoreBool = (char)1;
}

void it_cs_exit_CMockStopIgnore(void)
{
  Mock.it_cs_exit_IgnoreBool = (char)0;
}

void it_cs_exit_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_it_cs_exit_CALL_INSTANCE));
  CMOCK_it_cs_exit_CALL_INSTANCE* cmock_call_instance = (CMOCK_it_cs_exit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.it_cs_exit_CallInstance = CMock_Guts_MemChain(Mock.it_cs_exit_CallInstance, cmock_guts_index);
  Mock.it_cs_exit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

