/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockfdcan.h"

static const char* CMockString_MX_FDCAN1_Init = "MX_FDCAN1_Init";
static const char* CMockString_can_send = "can_send";
static const char* CMockString_data = "data";
static const char* CMockString_frame_type = "frame_type";
static const char* CMockString_id = "id";
static const char* CMockString_size = "size";

typedef struct _CMOCK_MX_FDCAN1_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_MX_FDCAN1_Init_CALL_INSTANCE;

typedef struct _CMOCK_can_send_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CanCommReturnCode ReturnVal;
  can_id_t Expected_id;
  CanFrameType Expected_frame_type;
  const uint8_t* Expected_data;
  size_t Expected_size;

} CMOCK_can_send_CALL_INSTANCE;

static struct MockfdcanInstance
{
  char MX_FDCAN1_Init_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE MX_FDCAN1_Init_CallInstance;
  char can_send_IgnoreBool;
  CanCommReturnCode can_send_FinalReturn;
  CMOCK_MEM_INDEX_TYPE can_send_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockfdcan_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.MX_FDCAN1_Init_CallInstance;
  if (Mock.MX_FDCAN1_Init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MX_FDCAN1_Init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.can_send_CallInstance;
  if (Mock.can_send_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_can_send);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockfdcan_Init(void)
{
  Mockfdcan_Destroy();
}

void Mockfdcan_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void MX_FDCAN1_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MX_FDCAN1_Init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MX_FDCAN1_Init);
  cmock_call_instance = (CMOCK_MX_FDCAN1_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MX_FDCAN1_Init_CallInstance);
  Mock.MX_FDCAN1_Init_CallInstance = CMock_Guts_MemNext(Mock.MX_FDCAN1_Init_CallInstance);
  if (Mock.MX_FDCAN1_Init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void MX_FDCAN1_Init_CMockIgnore(void)
{
  Mock.MX_FDCAN1_Init_IgnoreBool = (char)1;
}

void MX_FDCAN1_Init_CMockStopIgnore(void)
{
  Mock.MX_FDCAN1_Init_IgnoreBool = (char)0;
}

void MX_FDCAN1_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MX_FDCAN1_Init_CALL_INSTANCE));
  CMOCK_MX_FDCAN1_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_MX_FDCAN1_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MX_FDCAN1_Init_CallInstance = CMock_Guts_MemChain(Mock.MX_FDCAN1_Init_CallInstance, cmock_guts_index);
  Mock.MX_FDCAN1_Init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

CanCommReturnCode can_send(can_id_t id, CanFrameType frame_type, const uint8_t* data, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_can_send_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_can_send);
  cmock_call_instance = (CMOCK_can_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.can_send_CallInstance);
  Mock.can_send_CallInstance = CMock_Guts_MemNext(Mock.can_send_CallInstance);
  if (Mock.can_send_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.can_send_FinalReturn;
    memcpy((void*)(&Mock.can_send_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(CanCommReturnCode[sizeof(cmock_call_instance->ReturnVal) == sizeof(CanCommReturnCode) ? 1 : -1])); /* add CanCommReturnCode to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_can_send,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(can_id_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_can_send,CMockString_frame_type);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_frame_type), (void*)(&frame_type), sizeof(CanFrameType), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_can_send,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_can_send,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_can_send(CMOCK_can_send_CALL_INSTANCE* cmock_call_instance, can_id_t id, CanFrameType frame_type, const uint8_t* data, size_t size);
void CMockExpectParameters_can_send(CMOCK_can_send_CALL_INSTANCE* cmock_call_instance, can_id_t id, CanFrameType frame_type, const uint8_t* data, size_t size)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(can_id_t[sizeof(id) == sizeof(can_id_t) ? 1 : -1])); /* add can_id_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_frame_type), (void*)(&frame_type),
         sizeof(CanFrameType[sizeof(frame_type) == sizeof(CanFrameType) ? 1 : -1])); /* add CanFrameType to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void can_send_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, CanCommReturnCode cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_can_send_CALL_INSTANCE));
  CMOCK_can_send_CALL_INSTANCE* cmock_call_instance = (CMOCK_can_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.can_send_CallInstance = CMock_Guts_MemChain(Mock.can_send_CallInstance, cmock_guts_index);
  Mock.can_send_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.can_send_IgnoreBool = (char)1;
}

void can_send_CMockStopIgnore(void)
{
  if(Mock.can_send_IgnoreBool)
    Mock.can_send_CallInstance = CMock_Guts_MemNext(Mock.can_send_CallInstance);
  Mock.can_send_IgnoreBool = (char)0;
}

void can_send_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, can_id_t id, CanFrameType frame_type, const uint8_t* data, size_t size, CanCommReturnCode cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_can_send_CALL_INSTANCE));
  CMOCK_can_send_CALL_INSTANCE* cmock_call_instance = (CMOCK_can_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.can_send_CallInstance = CMock_Guts_MemChain(Mock.can_send_CallInstance, cmock_guts_index);
  Mock.can_send_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_can_send(cmock_call_instance, id, frame_type, data, size);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(CanCommReturnCode[sizeof(cmock_to_return) == sizeof(CanCommReturnCode) ? 1 : -1])); /* add CanCommReturnCode to :treat_as_array if this causes an error */
}

