/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockspi.h"

static const char* CMockString_MX_SPI3_Init = "MX_SPI3_Init";
static const char* CMockString_data = "data";
static const char* CMockString_out = "out";
static const char* CMockString_out_size = "out_size";
static const char* CMockString_size = "size";
static const char* CMockString_spi_send = "spi_send";
static const char* CMockString_spi_send_and_receive = "spi_send_and_receive";

typedef struct _CMOCK_MX_SPI3_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_MX_SPI3_Init_CALL_INSTANCE;

typedef struct _CMOCK_spi_send_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t* Expected_data;
  size_t Expected_size;

} CMOCK_spi_send_CALL_INSTANCE;

typedef struct _CMOCK_spi_send_and_receive_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t* Expected_data;
  uint8_t* Expected_out;
  size_t Expected_size;
  size_t Expected_out_size;

} CMOCK_spi_send_and_receive_CALL_INSTANCE;

static struct MockspiInstance
{
  char MX_SPI3_Init_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE MX_SPI3_Init_CallInstance;
  char spi_send_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE spi_send_CallInstance;
  char spi_send_and_receive_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE spi_send_and_receive_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockspi_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.MX_SPI3_Init_CallInstance;
  if (Mock.MX_SPI3_Init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MX_SPI3_Init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.spi_send_CallInstance;
  if (Mock.spi_send_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_spi_send);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.spi_send_and_receive_CallInstance;
  if (Mock.spi_send_and_receive_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_spi_send_and_receive);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockspi_Init(void)
{
  Mockspi_Destroy();
}

void Mockspi_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void MX_SPI3_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MX_SPI3_Init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MX_SPI3_Init);
  cmock_call_instance = (CMOCK_MX_SPI3_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MX_SPI3_Init_CallInstance);
  Mock.MX_SPI3_Init_CallInstance = CMock_Guts_MemNext(Mock.MX_SPI3_Init_CallInstance);
  if (Mock.MX_SPI3_Init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void MX_SPI3_Init_CMockIgnore(void)
{
  Mock.MX_SPI3_Init_IgnoreBool = (char)1;
}

void MX_SPI3_Init_CMockStopIgnore(void)
{
  Mock.MX_SPI3_Init_IgnoreBool = (char)0;
}

void MX_SPI3_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MX_SPI3_Init_CALL_INSTANCE));
  CMOCK_MX_SPI3_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_MX_SPI3_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MX_SPI3_Init_CallInstance = CMock_Guts_MemChain(Mock.MX_SPI3_Init_CallInstance, cmock_guts_index);
  Mock.MX_SPI3_Init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void spi_send(uint8_t* data, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spi_send_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_spi_send);
  cmock_call_instance = (CMOCK_spi_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spi_send_CallInstance);
  Mock.spi_send_CallInstance = CMock_Guts_MemNext(Mock.spi_send_CallInstance);
  if (Mock.spi_send_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_spi_send,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_spi_send,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_spi_send(CMOCK_spi_send_CALL_INSTANCE* cmock_call_instance, uint8_t* data, size_t size);
void CMockExpectParameters_spi_send(CMOCK_spi_send_CALL_INSTANCE* cmock_call_instance, uint8_t* data, size_t size)
{
  cmock_call_instance->Expected_data = data;
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void spi_send_CMockIgnore(void)
{
  Mock.spi_send_IgnoreBool = (char)1;
}

void spi_send_CMockStopIgnore(void)
{
  Mock.spi_send_IgnoreBool = (char)0;
}

void spi_send_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t* data, size_t size)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_send_CALL_INSTANCE));
  CMOCK_spi_send_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_send_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_send_CallInstance = CMock_Guts_MemChain(Mock.spi_send_CallInstance, cmock_guts_index);
  Mock.spi_send_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_spi_send(cmock_call_instance, data, size);
}

void spi_send_and_receive(uint8_t* data, uint8_t* out, size_t size, size_t out_size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spi_send_and_receive_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_spi_send_and_receive);
  cmock_call_instance = (CMOCK_spi_send_and_receive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spi_send_and_receive_CallInstance);
  Mock.spi_send_and_receive_CallInstance = CMock_Guts_MemNext(Mock.spi_send_and_receive_CallInstance);
  if (Mock.spi_send_and_receive_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_spi_send_and_receive,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_spi_send_and_receive,CMockString_out);
    if (cmock_call_instance->Expected_out == NULL)
      { UNITY_TEST_ASSERT_NULL(out, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_out, out, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_spi_send_and_receive,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_spi_send_and_receive,CMockString_out_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_out_size), (void*)(&out_size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_spi_send_and_receive(CMOCK_spi_send_and_receive_CALL_INSTANCE* cmock_call_instance, uint8_t* data, uint8_t* out, size_t size, size_t out_size);
void CMockExpectParameters_spi_send_and_receive(CMOCK_spi_send_and_receive_CALL_INSTANCE* cmock_call_instance, uint8_t* data, uint8_t* out, size_t size, size_t out_size)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_out = out;
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_out_size), (void*)(&out_size),
         sizeof(size_t[sizeof(out_size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void spi_send_and_receive_CMockIgnore(void)
{
  Mock.spi_send_and_receive_IgnoreBool = (char)1;
}

void spi_send_and_receive_CMockStopIgnore(void)
{
  Mock.spi_send_and_receive_IgnoreBool = (char)0;
}

void spi_send_and_receive_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t* data, uint8_t* out, size_t size, size_t out_size)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_send_and_receive_CALL_INSTANCE));
  CMOCK_spi_send_and_receive_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_send_and_receive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_send_and_receive_CallInstance = CMock_Guts_MemChain(Mock.spi_send_and_receive_CallInstance, cmock_guts_index);
  Mock.spi_send_and_receive_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_spi_send_and_receive(cmock_call_instance, data, out, size, out_size);
}

