/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockadc.h"

static const char* CMockString_MX_ADC1_Init = "MX_ADC1_Init";
static const char* CMockString_MX_ADC2_Init = "MX_ADC2_Init";
static const char* CMockString_MX_ADC3_Init = "MX_ADC3_Init";
static const char* CMockString_adc_read_cellboard_id = "adc_read_cellboard_id";
static const char* CMockString_out = "out";

typedef struct _CMOCK_MX_ADC1_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_MX_ADC1_Init_CALL_INSTANCE;

typedef struct _CMOCK_MX_ADC2_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_MX_ADC2_Init_CALL_INSTANCE;

typedef struct _CMOCK_MX_ADC3_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_MX_ADC3_Init_CALL_INSTANCE;

typedef struct _CMOCK_adc_read_cellboard_id_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  AdcReturnCode ReturnVal;
  CellboardId* Expected_out;

} CMOCK_adc_read_cellboard_id_CALL_INSTANCE;

static struct MockadcInstance
{
  char MX_ADC1_Init_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE MX_ADC1_Init_CallInstance;
  char MX_ADC2_Init_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE MX_ADC2_Init_CallInstance;
  char MX_ADC3_Init_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE MX_ADC3_Init_CallInstance;
  char adc_read_cellboard_id_IgnoreBool;
  AdcReturnCode adc_read_cellboard_id_FinalReturn;
  CMOCK_MEM_INDEX_TYPE adc_read_cellboard_id_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockadc_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.MX_ADC1_Init_CallInstance;
  if (Mock.MX_ADC1_Init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MX_ADC1_Init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.MX_ADC2_Init_CallInstance;
  if (Mock.MX_ADC2_Init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MX_ADC2_Init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.MX_ADC3_Init_CallInstance;
  if (Mock.MX_ADC3_Init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MX_ADC3_Init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.adc_read_cellboard_id_CallInstance;
  if (Mock.adc_read_cellboard_id_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_adc_read_cellboard_id);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockadc_Init(void)
{
  Mockadc_Destroy();
}

void Mockadc_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void MX_ADC1_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MX_ADC1_Init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MX_ADC1_Init);
  cmock_call_instance = (CMOCK_MX_ADC1_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MX_ADC1_Init_CallInstance);
  Mock.MX_ADC1_Init_CallInstance = CMock_Guts_MemNext(Mock.MX_ADC1_Init_CallInstance);
  if (Mock.MX_ADC1_Init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void MX_ADC1_Init_CMockIgnore(void)
{
  Mock.MX_ADC1_Init_IgnoreBool = (char)1;
}

void MX_ADC1_Init_CMockStopIgnore(void)
{
  Mock.MX_ADC1_Init_IgnoreBool = (char)0;
}

void MX_ADC1_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MX_ADC1_Init_CALL_INSTANCE));
  CMOCK_MX_ADC1_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_MX_ADC1_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MX_ADC1_Init_CallInstance = CMock_Guts_MemChain(Mock.MX_ADC1_Init_CallInstance, cmock_guts_index);
  Mock.MX_ADC1_Init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void MX_ADC2_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MX_ADC2_Init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MX_ADC2_Init);
  cmock_call_instance = (CMOCK_MX_ADC2_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MX_ADC2_Init_CallInstance);
  Mock.MX_ADC2_Init_CallInstance = CMock_Guts_MemNext(Mock.MX_ADC2_Init_CallInstance);
  if (Mock.MX_ADC2_Init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void MX_ADC2_Init_CMockIgnore(void)
{
  Mock.MX_ADC2_Init_IgnoreBool = (char)1;
}

void MX_ADC2_Init_CMockStopIgnore(void)
{
  Mock.MX_ADC2_Init_IgnoreBool = (char)0;
}

void MX_ADC2_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MX_ADC2_Init_CALL_INSTANCE));
  CMOCK_MX_ADC2_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_MX_ADC2_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MX_ADC2_Init_CallInstance = CMock_Guts_MemChain(Mock.MX_ADC2_Init_CallInstance, cmock_guts_index);
  Mock.MX_ADC2_Init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void MX_ADC3_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MX_ADC3_Init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MX_ADC3_Init);
  cmock_call_instance = (CMOCK_MX_ADC3_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MX_ADC3_Init_CallInstance);
  Mock.MX_ADC3_Init_CallInstance = CMock_Guts_MemNext(Mock.MX_ADC3_Init_CallInstance);
  if (Mock.MX_ADC3_Init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void MX_ADC3_Init_CMockIgnore(void)
{
  Mock.MX_ADC3_Init_IgnoreBool = (char)1;
}

void MX_ADC3_Init_CMockStopIgnore(void)
{
  Mock.MX_ADC3_Init_IgnoreBool = (char)0;
}

void MX_ADC3_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MX_ADC3_Init_CALL_INSTANCE));
  CMOCK_MX_ADC3_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_MX_ADC3_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MX_ADC3_Init_CallInstance = CMock_Guts_MemChain(Mock.MX_ADC3_Init_CallInstance, cmock_guts_index);
  Mock.MX_ADC3_Init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

AdcReturnCode adc_read_cellboard_id(CellboardId* out)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_adc_read_cellboard_id_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_adc_read_cellboard_id);
  cmock_call_instance = (CMOCK_adc_read_cellboard_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.adc_read_cellboard_id_CallInstance);
  Mock.adc_read_cellboard_id_CallInstance = CMock_Guts_MemNext(Mock.adc_read_cellboard_id_CallInstance);
  if (Mock.adc_read_cellboard_id_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.adc_read_cellboard_id_FinalReturn;
    memcpy((void*)(&Mock.adc_read_cellboard_id_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(AdcReturnCode[sizeof(cmock_call_instance->ReturnVal) == sizeof(AdcReturnCode) ? 1 : -1])); /* add AdcReturnCode to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_adc_read_cellboard_id,CMockString_out);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_out), (void*)(out), sizeof(CellboardId), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_adc_read_cellboard_id(CMOCK_adc_read_cellboard_id_CALL_INSTANCE* cmock_call_instance, CellboardId* out);
void CMockExpectParameters_adc_read_cellboard_id(CMOCK_adc_read_cellboard_id_CALL_INSTANCE* cmock_call_instance, CellboardId* out)
{
  cmock_call_instance->Expected_out = out;
}

void adc_read_cellboard_id_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, AdcReturnCode cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_adc_read_cellboard_id_CALL_INSTANCE));
  CMOCK_adc_read_cellboard_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_adc_read_cellboard_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.adc_read_cellboard_id_CallInstance = CMock_Guts_MemChain(Mock.adc_read_cellboard_id_CallInstance, cmock_guts_index);
  Mock.adc_read_cellboard_id_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.adc_read_cellboard_id_IgnoreBool = (char)1;
}

void adc_read_cellboard_id_CMockStopIgnore(void)
{
  if(Mock.adc_read_cellboard_id_IgnoreBool)
    Mock.adc_read_cellboard_id_CallInstance = CMock_Guts_MemNext(Mock.adc_read_cellboard_id_CallInstance);
  Mock.adc_read_cellboard_id_IgnoreBool = (char)0;
}

void adc_read_cellboard_id_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CellboardId* out, AdcReturnCode cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_adc_read_cellboard_id_CALL_INSTANCE));
  CMOCK_adc_read_cellboard_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_adc_read_cellboard_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.adc_read_cellboard_id_CallInstance = CMock_Guts_MemChain(Mock.adc_read_cellboard_id_CallInstance, cmock_guts_index);
  Mock.adc_read_cellboard_id_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_adc_read_cellboard_id(cmock_call_instance, out);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(AdcReturnCode[sizeof(cmock_to_return) == sizeof(AdcReturnCode) ? 1 : -1])); /* add AdcReturnCode to :treat_as_array if this causes an error */
}

