[platformio]
src_dir = .
include_dir = .

[env:base]
platform = ststm32
board = stm32g4a1
upload_protocol = stlink
monitor_speed = 115200

board_build.ldscript = STM32G4A1KEUx_FLASH.ld

build_flags =
    -DUSE_HAL_DRIVER
    -DSCNu8=\"hhu\"
    -DSCNi8=\"hhi\"

    -ICore/Inc
    -ICore/Inc/common
    -ICore/Inc/bms
    -ICore/Inc/bms/errors
    -ICore/Inc/bms/monitor
    -ICore/Inc/bms/timebase
    -ICore/Lib
    -ICore/Lib/micro-libs/bms-monitor/inc
    -ICore/Lib/micro-libs/ring-buffer/inc
    -ICore/Lib/micro-libs/errorlib/inc
    -ICore/Lib/micro-libs/blinky/inc
    -ICore/Lib/micro-libs/min-heap/inc
    -ICore/Lib/micro-libs/timer-utils
    -IDrivers/CMSIS/Device/ST/STM32G4xx/Include
    -IDrivers/CMSIS/Core/Include
    -IDrivers/STM32G4xx_HAL_Driver/Inc
    -ICore/Lib/can/lib/bms
    -ICore/Lib/can/lib

build_src_filter =
    +<Core/Src/**>
    +<Core/Lib/**>
    +<Drivers/STM32G4xx_HAL_Driver/Src/*>

    ; exclude test/example folders
    -<**/micro-libs/**>

    +<**/micro-libs/bms-monitor/**>
    +<**/micro-libs/ring-buffer/src>
    +<**/micro-libs/errorlib/src>
    +<**/micro-libs/blinky/src>
    +<**/micro-libs/min-heap/src>
    +<**/micro-libs/timer-utils>
    -<**/micro-libs/**/tests/**>
    -<**/micro-libs/**/test/**>
    -<**/micro-libs/**/example/**>
    -<**/micro-libs/**/examples/**>

    ; exclude CAN cpp duplicates
    -<**/bms_utils.cpp>
    -<**/inverters_utils.cpp>
    -<**/primary_utils.cpp>
    -<**/secondary_utils.cpp>
    -<**/simulator_utils.cpp>

    +<startup_stm32g4a1xx.s>

    -<Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_msp_template.c>
    -<Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_timebase_tim_template.c>


[env:balancing_tests]
platform = native
test_framework = unity
test_build_src = true


build_flags =
    -DUSE_HAL_DRIVER
    -DSCNu8=\"hhu\"
    -DSCNi8=\"hhi\"

    -DBALANCING_TESTS=1

    -D_STATIC=
    -Itests/test_helpers.h
    -ICore/Inc/bms
    -ICore/Inc/bms/errors
    -ICore/Inc/bms/monitor
    -ICore/Inc/bms/timebase
    -ICore/Inc/common
    -ICore/Lib
    -ICore/Lib/micro-libs/bms-monitor/inc
    -ICore/Lib/micro-libs/ring-buffer/inc
    -ICore/Lib/micro-libs/errorlib/inc
    -ICore/Lib/micro-libs/blinky/inc
    -ICore/Lib/micro-libs/min-heap/inc
    -ICore/Lib/can/lib/bms
    -ICore/Lib/can/lib

build_src_filter =
    +<Core/Src/bms/**>
    +<Core/Src/common/**>
    +<Core/Lib/bms/**>
    +<Core/Lib/common/**>

    +<Core/Lib/can/lib/**>


    -<**/micro-libs/**>
    
    +<**/micro-libs/bms-monitor/**>
    +<**/micro-libs/ring-buffer/src>
    +<**/micro-libs/errorlib/src>
    +<**/micro-libs/blinky/src>
    +<**/micro-libs/min-heap/src>
    -<**/micro-libs/**/tests/**>
    -<**/micro-libs/**/test/**>
    -<**/micro-libs/**/example/**>
    -<**/micro-libs/**/examples/**>

    ; exclude CAN cpp duplicates
    -<**/bms_utils.cpp>
    -<**/inverters_utils.cpp>
    -<**/primary_utils.cpp>
    -<**/secondary_utils.cpp>
    -<**/simulator_utils.cpp>

[env:temperature_tests]
platform = native
test_framework = unity
test_build_src = true


build_flags =
    -DUSE_HAL_DRIVER
    -DSCNu8=\"hhu\"
    -DSCNi8=\"hhi\"

    -DTEMP_TESTS=1

    -D_STATIC=
    -Itests/test_helpers.h
    -ICore/Inc/bms
    -ICore/Inc/bms/errors
    -ICore/Inc/bms/monitor
    -ICore/Inc/bms/timebase
    -ICore/Inc/common
    -ICore/Lib
    -ICore/Lib/micro-libs/bms-monitor/inc
    -ICore/Lib/micro-libs/ring-buffer/inc
    -ICore/Lib/micro-libs/errorlib/inc
    -ICore/Lib/micro-libs/blinky/inc
    -ICore/Lib/micro-libs/min-heap/inc
    -ICore/Lib/can/lib/bms
    -ICore/Lib/can/lib

build_src_filter =
    +<Core/Src/bms/**>
    +<Core/Src/common/**>
    +<Core/Lib/bms/**>
    +<Core/Lib/common/**>

    +<Core/Lib/can/lib/**>


    -<**/micro-libs/**>
    
    +<**/micro-libs/bms-monitor/**>
    +<**/micro-libs/ring-buffer/src>
    +<**/micro-libs/errorlib/src>
    +<**/micro-libs/blinky/src>
    +<**/micro-libs/min-heap/src>
    -<**/micro-libs/**/tests/**>
    -<**/micro-libs/**/test/**>
    -<**/micro-libs/**/example/**>
    -<**/micro-libs/**/examples/**>

    ; exclude CAN cpp duplicates
    -<**/bms_utils.cpp>
    -<**/inverters_utils.cpp>
    -<**/primary_utils.cpp>
    -<**/secondary_utils.cpp>
    -<**/simulator_utils.cpp>

    


[env:bms_manager_tests]
platform = native
test_framework = unity
test_build_src = true


build_flags =
    -DUSE_HAL_DRIVER
    -DSCNu8=\"hhu\"
    -DSCNi8=\"hhi\"

    -DBMS_MANAGER_TESTS=1

    -D_STATIC=
    -Itests/test_helpers.h
    -ICore/Inc/bms
    -ICore/Inc/bms/errors
    -ICore/Inc/bms/monitor
    -ICore/Inc/bms/timebase
    -ICore/Inc/common
    -ICore/Lib
    -ICore/Lib/micro-libs/bms-monitor/inc
    -ICore/Lib/micro-libs/ring-buffer/inc
    -ICore/Lib/micro-libs/errorlib/inc
    -ICore/Lib/micro-libs/blinky/inc
    -ICore/Lib/micro-libs/min-heap/inc
    -ICore/Lib/can/lib/bms
    -ICore/Lib/can/lib

build_src_filter =
    +<Core/Src/bms/**>
    +<Core/Src/common/**>
    +<Core/Lib/bms/**>
    +<Core/Lib/common/**>

    +<Core/Lib/can/lib/**>


    -<**/micro-libs/**>
    
    +<**/micro-libs/bms-monitor/**>
    +<**/micro-libs/ring-buffer/src>
    +<**/micro-libs/errorlib/src>
    +<**/micro-libs/blinky/src>
    +<**/micro-libs/min-heap/src>
    -<**/micro-libs/**/tests/**>
    -<**/micro-libs/**/test/**>
    -<**/micro-libs/**/example/**>
    -<**/micro-libs/**/examples/**>

    ; exclude CAN cpp duplicates
    -<**/bms_utils.cpp>
    -<**/inverters_utils.cpp>
    -<**/primary_utils.cpp>
    -<**/secondary_utils.cpp>
    -<**/simulator_utils.cpp>