[platformio]
src_dir = .
include_dir = .

[env:bootloader]
platform = ststm32
board = stm32g4a1
upload_protocol = stlink
monitor_speed = 115200
board_build.ldscript = ./hv-bms-cellboard-bootloader-sw/STM32G4A1KEUx_FLASH.ld

build_flags =

    -Wl,-Map,./.pio/build/bootloader/output_bootloader.map

    -DUSE_HAL_DRIVER
    -DUSE_FULL_LL_DRIVER
    -Ihv-bms-cellboard-bootloader-sw/Core/Inc
    -Ihv-bms-cellboard-bootloader-sw/Core/Inc/libopenblt

    -Ihv-bms-cellboard-bootloader-sw/Drivers/CMSIS/Device/ST/STM32G4xx/Include
    -Ihv-bms-cellboard-bootloader-sw/Drivers/CMSIS/Core/Include
    -Ihv-bms-cellboard-bootloader-sw/Drivers/STM32G4xx_HAL_Driver/Inc

build_src_filter =
    +<hv-bms-cellboard-bootloader-sw/Core/Src/**>
    +<hv-bms-cellboard-bootloader-sw/Drivers/STM32G4xx_HAL_Driver/Src/**>
    +<hv-bms-cellboard-bootloader-sw/startup_stm32g4a1xx.s>

    -<hv-bms-cellboard-bootloader-sw/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_msp_template.c>
    -<hv-bms-cellboard-bootloader-sw/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_timebase_tim_template.c>

[env:base]
platform = ststm32
board = stm32g4a1
upload_protocol = stlink
monitor_speed = 115200

board_build.ldscript = ./Core/STM32G4A1KEUx_FLASH.ld
board_upload.offset = 0x08003000

build_flags =

    -Wl,-Map,./.pio/build/base/output_base.map

    -DUSE_HAL_DRIVER
    -DSCNu8=\"hhu\"
    -DSCNi8=\"hhi\"

    -ICore/Inc
    -ICore/Inc/common
    -ICore/Inc/bms
    -ICore/Inc/bms/errors
    -ICore/Inc/bms/monitor
    -ICore/Inc/bms/timebase
    -ICore/Lib
    -ICore/Lib/micro-libs/bms-monitor/inc
    -ICore/Lib/micro-libs/ring-buffer/inc
    -ICore/Lib/micro-libs/errorlib/inc
    -ICore/Lib/micro-libs/blinky/inc
    -ICore/Lib/micro-libs/min-heap/inc
    -ICore/Lib/micro-libs/timer-utils
    -IDrivers/CMSIS/Device/ST/STM32G4xx/Include
    -IDrivers/CMSIS/Core/Include
    -IDrivers/STM32G4xx_HAL_Driver/Inc
    -ICore/Lib/can/lib/bms
    -ICore/Lib/can/lib

build_src_filter =
    +<Core/Src/**>
    +<Core/Lib/**>
    +<Drivers/STM32G4xx_HAL_Driver/Src/*>

    ; exclude test/example folders
    -<**/micro-libs/**>

    +<**/micro-libs/bms-monitor/**>
    +<**/micro-libs/ring-buffer/src>
    +<**/micro-libs/errorlib/src>
    +<**/micro-libs/blinky/src>
    +<**/micro-libs/min-heap/src>
    +<**/micro-libs/timer-utils>
    -<**/micro-libs/**/tests/**>
    -<**/micro-libs/**/test/**>
    -<**/micro-libs/**/example/**>
    -<**/micro-libs/**/examples/**>

    ; exclude CAN cpp duplicates
    -<**/bms_utils.cpp>
    -<**/inverters_utils.cpp>
    -<**/primary_utils.cpp>
    -<**/secondary_utils.cpp>
    -<**/simulator_utils.cpp>

    +<./Core/startup_stm32g4a1xx.s>

    -<Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_msp_template.c>
    -<Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_timebase_tim_template.c>


[env:tests]
platform = native
test_framework = unity
test_build_src = true

build_flags =
    -DUSE_HAL_DRIVER
    -DSCNu8=\"hhu\"
    -DSCNi8=\"hhi\"
    -D_STATIC=
    -Itests/test_helpers.h
    -ICore/Inc/bms
    -ICore/Inc/bms/errors
    -ICore/Inc/bms/monitor
    -ICore/Inc/bms/timebase
    -ICore/Inc/common
    -ICore/Lib
    -ICore/Lib/micro-libs/bms-monitor/inc
    -ICore/Lib/micro-libs/ring-buffer/inc
    -ICore/Lib/micro-libs/errorlib/inc
    -ICore/Lib/micro-libs/blinky/inc
    -ICore/Lib/micro-libs/min-heap/inc
    -ICore/Lib/can/lib/bms
    -ICore/Lib/can/lib

build_src_filter =
    +<Core/Src/bms/**>
    +<Core/Src/common/**>
    +<Core/Lib/bms/**>
    +<Core/Lib/common/**>

    +<Core/Lib/can/lib/**>

    -<**/micro-libs/**>
    
    +<**/micro-libs/bms-monitor/**>
    +<**/micro-libs/ring-buffer/src>
    +<**/micro-libs/errorlib/src>
    +<**/micro-libs/blinky/src>
    +<**/micro-libs/min-heap/src>
    -<**/micro-libs/**/tests/**>
    -<**/micro-libs/**/test/**>
    -<**/micro-libs/**/example/**>
    -<**/micro-libs/**/examples/**>

    ; exclude CAN cpp duplicates
    -<**/bms_utils.cpp>
    -<**/inverters_utils.cpp>
    -<**/primary_utils.cpp>
    -<**/secondary_utils.cpp>
    -<**/simulator_utils.cpp>

[env:balancing_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DBALANCING_TESTS=1


[env:temperature_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DTEMP_TESTS=1


[env:bms_manager_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DBMS_MANAGER_TESTS=1

[env:can_comm_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DCAN_COMM_TESTS=1

[env:identity_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DIDENTITY_TESTS=1

[env:led_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DLED_TESTS=1

[env:programmer_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DPROGRAMMER_TESTS=1

[env:volt_tests]
extends = env:tests
build_flags =
    ${env:tests.build_flags}
    -DVOLT_TESTS=1