[platformio]
src_dir = .
include_dir = .
default_envs = base


[env:bootloader]
platform = ststm32
board = stm32g4a1
upload_protocol = stlink
monitor_speed = 115200
board_build.ldscript = ./hv-bms-cellboard-bootloader-sw/STM32G4A1KEUx_FLASH.ld
lib_deps =
    https://github.com/eagletrt/libbms-monitor-sw.git#dev


build_flags =

    -Wl,-Map,./.pio/build/bootloader/output_bootloader.map

    -DUSE_HAL_DRIVER
    -DUSE_FULL_LL_DRIVER
    -Ihv-bms-cellboard-bootloader-sw/Core/Inc
    -Ihv-bms-cellboard-bootloader-sw/Core/Inc/libopenblt

    -Ihv-bms-cellboard-bootloader-sw/Drivers/CMSIS/Device/ST/STM32G4xx/Include
    -Ihv-bms-cellboard-bootloader-sw/Drivers/CMSIS/Core/Include
    -Ihv-bms-cellboard-bootloader-sw/Drivers/STM32G4xx_HAL_Driver/Inc

build_src_filter =
    +<hv-bms-cellboard-bootloader-sw/Core/Src/**>
    +<hv-bms-cellboard-bootloader-sw/Drivers/STM32G4xx_HAL_Driver/Src/**>
    +<hv-bms-cellboard-bootloader-sw/startup_stm32g4a1xx.s>

    -<hv-bms-cellboard-bootloader-sw/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_msp_template.c>
    -<hv-bms-cellboard-bootloader-sw/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_timebase_tim_template.c>

[env:base]
platform = ststm32
board = stm32g4a1
upload_protocol = stlink
monitor_speed = 115200
lib_deps =
    https://github.com/eagletrt/libbms-monitor-sw.git#dev

board_build.ldscript = ./STM32G4A1KEUx_FLASH_shifted.ld
board_upload.offset = 0x08003000

build_flags =

    -Wl,-Map,./.pio/build/base/output_base.map

    -DUSE_HAL_DRIVER
    -DSCNu8=\"hhu\"
    -DSCNi8=\"hhi\"
    -ICore/Inc/common
    -ICore/Inc
    -ICore/Inc/bms
    -ICore/Inc/bms/errors
    -ICore/Inc/bms/monitor
    -ICore/Inc/bms/timebase
    -ICore/Lib
    -ICore/Lib/micro-libs/ring-buffer/inc
    -ICore/Lib/micro-libs/errorlib/inc
    -ICore/Lib/micro-libs/blinky/inc
    -ICore/Lib/micro-libs/min-heap/inc
    -ICore/Lib/micro-libs/timer-utils
    -IDrivers/CMSIS/Device/ST/STM32G4xx/Include
    -IDrivers/CMSIS/Core/Include
    -IDrivers/STM32G4xx_HAL_Driver/Inc
    -ICore/Lib/can/lib/bms
    -ICore/Lib/can/lib

build_src_filter =
    +<Core/Src/**>
    +<Core/Lib/**>
    +<Drivers/STM32G4xx_HAL_Driver/Src/*>

    ; exclude test/example folders
    -<**/micro-libs/**>
    +<**/micro-libs/ring-buffer/src>
    +<**/micro-libs/errorlib/src>
    +<**/micro-libs/blinky/src>
    +<**/micro-libs/min-heap/src>
    +<**/micro-libs/timer-utils>
    -<**/micro-libs/**/tests/**>
    -<**/micro-libs/**/test/**>
    -<**/micro-libs/**/example/**>
    -<**/micro-libs/**/examples/**>

    ; exclude CAN cpp duplicates
    -<**/*_utils.cpp>

    +<./startup_stm32g4a1xx.s>

    -<Drivers/STM32G4xx_HAL_Driver/Src/*_template.c>


[env:tests]
platform = native
test_framework = unity
test_build_src = true
lib_deps =
    https://github.com/eagletrt/libbms-monitor-sw.git#dev

build_flags =
    -DUSE_HAL_DRIVER
    -DSCNu8=\"hhu\"
    -DSCNi8=\"hhi\"
    -D_STATIC=
    -ICore/Inc/bms
    -ICore/Inc/bms/errors
    -ICore/Inc/bms/monitor
    -ICore/Inc/bms/timebase
    -ICore/Inc/common
    -ICore/Lib
    -ICore/Lib/micro-libs/bms-monitor/inc
    -ICore/Lib/micro-libs/ring-buffer/inc
    -ICore/Lib/micro-libs/errorlib/inc
    -ICore/Lib/micro-libs/blinky/inc
    -ICore/Lib/micro-libs/min-heap/inc
    -ICore/Lib/can/lib/bms
    -ICore/Lib/can/lib

build_src_filter =
    +<Core/Src/bms/**>
    +<Core/Src/common/**>
    +<Core/Lib/bms/**>
    +<Core/Lib/common/**>

    +<Core/Lib/can/lib/**>

    -<**/micro-libs/**>
    
    +<**/micro-libs/bms-monitor/**>
    +<**/micro-libs/ring-buffer/src>
    +<**/micro-libs/errorlib/src>
    +<**/micro-libs/blinky/src>
    +<**/micro-libs/min-heap/src>
    -<**/micro-libs/**/tests/**>
    -<**/micro-libs/**/test/**>
    -<**/micro-libs/**/example/**>
    -<**/micro-libs/**/examples/**>

    ; exclude CAN cpp duplicates
    -<**/*_utils.cpp>
