/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockblinky.h"

static const char* CMockString_b = "b";
static const char* CMockString_blinky_enable = "blinky_enable";
static const char* CMockString_blinky_init = "blinky_init";
static const char* CMockString_blinky_repeat = "blinky_repeat";
static const char* CMockString_blinky_reset = "blinky_reset";
static const char* CMockString_blinky_routine = "blinky_routine";
static const char* CMockString_blinky_set_pattern = "blinky_set_pattern";
static const char* CMockString_enabled = "enabled";
static const char* CMockString_pattern = "pattern";
static const char* CMockString_repeat = "repeat";
static const char* CMockString_size = "size";
static const char* CMockString_state = "state";
static const char* CMockString_t = "t";

typedef struct _CMOCK_blinky_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Blinky* Expected_b;
  uint16_t* Expected_pattern;
  uint8_t Expected_size;
  bool Expected_repeat;
  BlinkyState Expected_state;

} CMOCK_blinky_init_CALL_INSTANCE;

typedef struct _CMOCK_blinky_enable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Blinky* Expected_b;
  bool Expected_enabled;

} CMOCK_blinky_enable_CALL_INSTANCE;

typedef struct _CMOCK_blinky_repeat_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Blinky* Expected_b;
  bool Expected_repeat;

} CMOCK_blinky_repeat_CALL_INSTANCE;

typedef struct _CMOCK_blinky_set_pattern_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Blinky* Expected_b;
  uint16_t* Expected_pattern;
  uint8_t Expected_size;

} CMOCK_blinky_set_pattern_CALL_INSTANCE;

typedef struct _CMOCK_blinky_reset_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Blinky* Expected_b;
  BlinkyState Expected_state;

} CMOCK_blinky_reset_CALL_INSTANCE;

typedef struct _CMOCK_blinky_routine_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  BlinkyState ReturnVal;
  Blinky* Expected_b;
  uint32_t Expected_t;

} CMOCK_blinky_routine_CALL_INSTANCE;

static struct MockblinkyInstance
{
  CMOCK_MEM_INDEX_TYPE blinky_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE blinky_enable_CallInstance;
  CMOCK_MEM_INDEX_TYPE blinky_repeat_CallInstance;
  CMOCK_MEM_INDEX_TYPE blinky_set_pattern_CallInstance;
  CMOCK_MEM_INDEX_TYPE blinky_reset_CallInstance;
  CMOCK_MEM_INDEX_TYPE blinky_routine_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockblinky_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.blinky_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_blinky_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.blinky_enable_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_blinky_enable);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.blinky_repeat_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_blinky_repeat);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.blinky_set_pattern_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_blinky_set_pattern);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.blinky_reset_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_blinky_reset);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.blinky_routine_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_blinky_routine);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockblinky_Init(void)
{
  Mockblinky_Destroy();
}

void Mockblinky_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void blinky_init(Blinky* b, uint16_t* pattern, uint8_t size, bool repeat, BlinkyState state)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_blinky_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_blinky_init);
  cmock_call_instance = (CMOCK_blinky_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.blinky_init_CallInstance);
  Mock.blinky_init_CallInstance = CMock_Guts_MemNext(Mock.blinky_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_blinky_init,CMockString_b);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_b), (void*)(b), sizeof(Blinky), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_blinky_init,CMockString_pattern);
    if (cmock_call_instance->Expected_pattern == NULL)
      { UNITY_TEST_ASSERT_NULL(pattern, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_pattern, pattern, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_blinky_init,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_size, size, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_blinky_init,CMockString_repeat);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_repeat, repeat, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_blinky_init,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(BlinkyState), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_blinky_init(CMOCK_blinky_init_CALL_INSTANCE* cmock_call_instance, Blinky* b, uint16_t* pattern, uint8_t size, bool repeat, BlinkyState state);
void CMockExpectParameters_blinky_init(CMOCK_blinky_init_CALL_INSTANCE* cmock_call_instance, Blinky* b, uint16_t* pattern, uint8_t size, bool repeat, BlinkyState state)
{
  cmock_call_instance->Expected_b = b;
  cmock_call_instance->Expected_pattern = pattern;
  cmock_call_instance->Expected_size = size;
  cmock_call_instance->Expected_repeat = repeat;
  memcpy((void*)(&cmock_call_instance->Expected_state), (void*)(&state),
         sizeof(BlinkyState[sizeof(state) == sizeof(BlinkyState) ? 1 : -1])); /* add BlinkyState to :treat_as_array if this causes an error */
}

void blinky_init_CMockExpect(UNITY_LINE_TYPE cmock_line, Blinky* b, uint16_t* pattern, uint8_t size, bool repeat, BlinkyState state)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_blinky_init_CALL_INSTANCE));
  CMOCK_blinky_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_blinky_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.blinky_init_CallInstance = CMock_Guts_MemChain(Mock.blinky_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_blinky_init(cmock_call_instance, b, pattern, size, repeat, state);
}

void blinky_enable(Blinky* b, bool enabled)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_blinky_enable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_blinky_enable);
  cmock_call_instance = (CMOCK_blinky_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.blinky_enable_CallInstance);
  Mock.blinky_enable_CallInstance = CMock_Guts_MemNext(Mock.blinky_enable_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_blinky_enable,CMockString_b);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_b), (void*)(b), sizeof(Blinky), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_blinky_enable,CMockString_enabled);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_enabled, enabled, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_blinky_enable(CMOCK_blinky_enable_CALL_INSTANCE* cmock_call_instance, Blinky* b, bool enabled);
void CMockExpectParameters_blinky_enable(CMOCK_blinky_enable_CALL_INSTANCE* cmock_call_instance, Blinky* b, bool enabled)
{
  cmock_call_instance->Expected_b = b;
  cmock_call_instance->Expected_enabled = enabled;
}

void blinky_enable_CMockExpect(UNITY_LINE_TYPE cmock_line, Blinky* b, bool enabled)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_blinky_enable_CALL_INSTANCE));
  CMOCK_blinky_enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_blinky_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.blinky_enable_CallInstance = CMock_Guts_MemChain(Mock.blinky_enable_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_blinky_enable(cmock_call_instance, b, enabled);
}

void blinky_repeat(Blinky* b, bool repeat)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_blinky_repeat_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_blinky_repeat);
  cmock_call_instance = (CMOCK_blinky_repeat_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.blinky_repeat_CallInstance);
  Mock.blinky_repeat_CallInstance = CMock_Guts_MemNext(Mock.blinky_repeat_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_blinky_repeat,CMockString_b);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_b), (void*)(b), sizeof(Blinky), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_blinky_repeat,CMockString_repeat);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_repeat, repeat, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_blinky_repeat(CMOCK_blinky_repeat_CALL_INSTANCE* cmock_call_instance, Blinky* b, bool repeat);
void CMockExpectParameters_blinky_repeat(CMOCK_blinky_repeat_CALL_INSTANCE* cmock_call_instance, Blinky* b, bool repeat)
{
  cmock_call_instance->Expected_b = b;
  cmock_call_instance->Expected_repeat = repeat;
}

void blinky_repeat_CMockExpect(UNITY_LINE_TYPE cmock_line, Blinky* b, bool repeat)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_blinky_repeat_CALL_INSTANCE));
  CMOCK_blinky_repeat_CALL_INSTANCE* cmock_call_instance = (CMOCK_blinky_repeat_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.blinky_repeat_CallInstance = CMock_Guts_MemChain(Mock.blinky_repeat_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_blinky_repeat(cmock_call_instance, b, repeat);
}

void blinky_set_pattern(Blinky* b, uint16_t* pattern, uint8_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_blinky_set_pattern_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_blinky_set_pattern);
  cmock_call_instance = (CMOCK_blinky_set_pattern_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.blinky_set_pattern_CallInstance);
  Mock.blinky_set_pattern_CallInstance = CMock_Guts_MemNext(Mock.blinky_set_pattern_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_blinky_set_pattern,CMockString_b);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_b), (void*)(b), sizeof(Blinky), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_blinky_set_pattern,CMockString_pattern);
    if (cmock_call_instance->Expected_pattern == NULL)
      { UNITY_TEST_ASSERT_NULL(pattern, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_pattern, pattern, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_blinky_set_pattern,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_size, size, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_blinky_set_pattern(CMOCK_blinky_set_pattern_CALL_INSTANCE* cmock_call_instance, Blinky* b, uint16_t* pattern, uint8_t size);
void CMockExpectParameters_blinky_set_pattern(CMOCK_blinky_set_pattern_CALL_INSTANCE* cmock_call_instance, Blinky* b, uint16_t* pattern, uint8_t size)
{
  cmock_call_instance->Expected_b = b;
  cmock_call_instance->Expected_pattern = pattern;
  cmock_call_instance->Expected_size = size;
}

void blinky_set_pattern_CMockExpect(UNITY_LINE_TYPE cmock_line, Blinky* b, uint16_t* pattern, uint8_t size)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_blinky_set_pattern_CALL_INSTANCE));
  CMOCK_blinky_set_pattern_CALL_INSTANCE* cmock_call_instance = (CMOCK_blinky_set_pattern_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.blinky_set_pattern_CallInstance = CMock_Guts_MemChain(Mock.blinky_set_pattern_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_blinky_set_pattern(cmock_call_instance, b, pattern, size);
}

void blinky_reset(Blinky* b, BlinkyState state)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_blinky_reset_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_blinky_reset);
  cmock_call_instance = (CMOCK_blinky_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.blinky_reset_CallInstance);
  Mock.blinky_reset_CallInstance = CMock_Guts_MemNext(Mock.blinky_reset_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_blinky_reset,CMockString_b);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_b), (void*)(b), sizeof(Blinky), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_blinky_reset,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(BlinkyState), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_blinky_reset(CMOCK_blinky_reset_CALL_INSTANCE* cmock_call_instance, Blinky* b, BlinkyState state);
void CMockExpectParameters_blinky_reset(CMOCK_blinky_reset_CALL_INSTANCE* cmock_call_instance, Blinky* b, BlinkyState state)
{
  cmock_call_instance->Expected_b = b;
  memcpy((void*)(&cmock_call_instance->Expected_state), (void*)(&state),
         sizeof(BlinkyState[sizeof(state) == sizeof(BlinkyState) ? 1 : -1])); /* add BlinkyState to :treat_as_array if this causes an error */
}

void blinky_reset_CMockExpect(UNITY_LINE_TYPE cmock_line, Blinky* b, BlinkyState state)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_blinky_reset_CALL_INSTANCE));
  CMOCK_blinky_reset_CALL_INSTANCE* cmock_call_instance = (CMOCK_blinky_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.blinky_reset_CallInstance = CMock_Guts_MemChain(Mock.blinky_reset_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_blinky_reset(cmock_call_instance, b, state);
}

BlinkyState blinky_routine(Blinky* b, uint32_t t)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_blinky_routine_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_blinky_routine);
  cmock_call_instance = (CMOCK_blinky_routine_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.blinky_routine_CallInstance);
  Mock.blinky_routine_CallInstance = CMock_Guts_MemNext(Mock.blinky_routine_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_blinky_routine,CMockString_b);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_b), (void*)(b), sizeof(Blinky), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_blinky_routine,CMockString_t);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_t, t, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_blinky_routine(CMOCK_blinky_routine_CALL_INSTANCE* cmock_call_instance, Blinky* b, uint32_t t);
void CMockExpectParameters_blinky_routine(CMOCK_blinky_routine_CALL_INSTANCE* cmock_call_instance, Blinky* b, uint32_t t)
{
  cmock_call_instance->Expected_b = b;
  cmock_call_instance->Expected_t = t;
}

void blinky_routine_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Blinky* b, uint32_t t, BlinkyState cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_blinky_routine_CALL_INSTANCE));
  CMOCK_blinky_routine_CALL_INSTANCE* cmock_call_instance = (CMOCK_blinky_routine_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.blinky_routine_CallInstance = CMock_Guts_MemChain(Mock.blinky_routine_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_blinky_routine(cmock_call_instance, b, t);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(BlinkyState[sizeof(cmock_to_return) == sizeof(BlinkyState) ? 1 : -1])); /* add BlinkyState to :treat_as_array if this causes an error */
}

